In [9]:
#importing required libraries

import pandas as pd
import matplotlib.pyplot as plt
#%matplotlin inline
import numpy as np

In [16]:
data=pd.read_csv("titanic.csv")

In [17]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
data['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [19]:
data=pd.get_dummies(data)

In [20]:
data.fillna(0,inplace=True)

In [21]:
data.shape

(891, 1731)

In [22]:
train=data[0:699]

In [23]:
test=data[700:890]

In [24]:
x_train=train.drop('Survived', axis=1)

In [25]:
true_p = test['Survived']

In [26]:
x_train

,PassengerId,Pclass,Age,SibSp,Parch,Fare,"Name_Abbing, Mr. Anthony","Name_Abbott, Mr. Rossmore Edward","Name_Abbott, Mrs. Stanton (Rosa Hunt)","Name_Abelson, Mr. Samuel",...,Cabin_F G73,Cabin_F2,Cabin_F33,Cabin_F38,Cabin_F4,Cabin_G6,Cabin_T,Embarked_C,Embarked_Q,Embarked_S
0,1,3,22.0,1,0,7.2500,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,2,1,38.0,1,0,71.2833,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,3,26.0,0,0,7.9250,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,4,1,35.0,1,0,53.1000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,5,3,35.0,0,0,8.0500,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,6,3,0.0,0,0,8.4583,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,7,1,54.0,0,0,51.8625,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,8,3,2.0,3,1,21.0750,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8,9,3,27.0,0,2,11.1333,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9,10,2,14.0,1,0,30.0708,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
10,11,3,4.0,1,1,16.7000,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
11,12,1,58.0,0,0,26.5500,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12,13,3,20.0,0,0,8.0500,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13,14,3,39.0,1,5,31.2750,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
14,15,3,14.0,0,0,7.8542,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
15,16,2,55.0,0,0,16.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,17,3,2.0,4,1,29.1250,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
17,18,2,0.0,0,0,13.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18,19,3,31.0,1,0,18.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,20,3,0.0,0,0,7.2250,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
20,21,2,35.0,0,0,26.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
21,22,2,34.0,0,0,13.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
22,23,3,15.0,0,0,8.0292,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
23,24,1,28.0,0,0,35.5000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24,25,3,8.0,3,1,21.0750,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,26,3,38.0,1,5,31.3875,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
26,27,3,0.0,0,0,7.2250,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
27,28,1,19.0,3,2,263.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
28,29,3,0.0,0,0,7.8792,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
29,30,3,0.0,0,0,7.8958,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669,670,1,0.0,1,0,52.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
670,671,2,40.0,1,1,39.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
671,672,1,31.0,1,0,52.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
672,673,2,70.0,0,0,10.5000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
673,674,2,31.0,0,0,13.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
674,675,2,0.0,0,0,0.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
675,676,3,18.0,0,0,7.7750,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
676,677,3,24.5,0,0,8.0500,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
677,678,3,18.0,0,0,9.8417,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
678,679,3,43.0,1,6,46.9000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
679,680,1,36.0,0,1,512.3292,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
680,681,3,0.0,0,0,8.1375,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
681,682,1,27.0,0,0,76.7292,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
682,683,3,20.0,0,0,9.2250,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
683,684,3,14.0,5,2,46.9000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
684,685,2,60.0,1,1,39.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
685,686,2,25.0,1,2,41.5792,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
686,687,3,14.0,4,1,39.6875,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
687,688,3,19.0,0,0,10.1708,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
688,689,3,18.0,0,0,7.7958,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
689,690,1,15.0,0,1,211.3375,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
690,691,1,31.0,1,0,57.0000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
691,692,3,4.0,0,1,13.4167,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
692,693,3,0.0,0,0,56.4958,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
693,694,3,25.0,0,0,7.2250,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
694,695,1,60.0,0,0,26.5500,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
695,696,2,52.0,0,0,13.5000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
696,697,3,44.0,0,0,8.0500,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
697,698,3,0.0,0,0,7.7333,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
698,699,1,49.0,1,1,110.8833,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [27]:
x_test

NameError: name 'x_test' is not defined

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
logreg=LogisticRegression()

In [30]:
logreg.fit(x_train,y_train)

NameError: name 'y_train' is not defined

In [31]:
pred=logreg.predict(x_test)

NameError: name 'x_test' is not defined

In [ ]:
pred

In [ ]:
logreg.score(x_test,true_p)

In [ ]:
logreg.score(x_train,y_train)